### ISSUE TITLE
Naming

### ISSUE THREAD

**Issue by mgcth** [Ingenjorsarbete-For-Klimatet/ifk-smhi#106]
## Description

Rename data to something more meaningful, e.g. station or table.

@docNord could you think of something for the 4 APIs we are accessing?

**Comment by docNord** [comment]
Table is probably safe, right?

**Comment by mgcth** [comment]
Maybe df then? Though it doesn't say much about what is in it.

**Comment by docNord** [comment]
Df makes sense
