### ISSUE TITLE
SMHI STRÅNG API not working correctly

### ISSUE THREAD

**Issue by mgcth** [Ingenjorsarbete-For-Klimatet/ifk-smhi#24]
From https://opendata.smhi.se/apidocs/strang/#point_multipoint this API call https://opendata-download-metanalys.smhi.se/api/category/strang1g/version/1/geotype/point/lon/16.158/lat/58.5812/parameter/118/data.json gives `no data found` as of now. One integration test in Strang fails because of it. Let's see if it gets fixed by SMHI.

**Comment by docNord** [comment]
There is now data available:

<html><body>


  |  
-- | --
0 |  
date_time | "2022-11-13T20:00:00Z"
value | 0
1 |  
date_time | "2022-11-13T21:00:00Z"
value | 0
2 |  
date_time | "2022-11-13T22:00:00Z"
value | 0
3 |  
date_time | "2022-11-13T23:00:00Z"
value | 0


</body>
</html>

with that, are we ok to close @mgcth ?

**Comment by mgcth** [comment]
I wonder if the STRÅNG API calls are lated to some time of the day, e.g. at some minutes after midnight it failed: https://github.com/Ingenjorsarbete-For-Klimatet/ifk-smhi/actions/runs/3510160420/jobs/5879744155.

**Comment by mgcth** [comment]
Working again.

**Comment by mgcth** [comment]
Strang integration test fails again just after midnight. We need to figure out why. I'll leave this open. See https://github.com/Ingenjorsarbete-For-Klimatet/ifk-smhi/actions/runs/3527955708/jobs/5917553705

**Comment by docNord** [comment]
I have emailed smhi. Let's see if they have any information on what is going on.

**Comment by mgcth** [comment]
Odd. A bit hard to debug, but I can't imagine our code _randomly_ changing the HTML request method.

**Comment by mgcth** [comment]
Here we go again: https://github.com/Ingenjorsarbete-For-Klimatet/ifk-smhi/actions/runs/3597318895/jobs/6058953177 at Thu, 01 Dec 2022 23:09:29 GMT. What is happening here?

**Comment by docNord** [comment]
This issue seems a bit stale. Ok to close @mgcth ?

**Comment by mgcth** [comment]
Yeah. But we will have issues with builds just after midnight. We can look more into it later.
