### ISSUE TITLE
Clean history from csv file

### ISSUE THREAD

**Issue by mgcth** [Ingenjorsarbete-For-Klimatet/ifk-smhi#32]
I'd like to clean our git history from this file https://github.com/Ingenjorsarbete-For-Klimatet/ifk-smhi/commit/e75202a00824653ea7160137999c8cd5bbbf8bbb. But to do that, I'd like to close all PRs first. When history is rewritten (which will probably change all commit sha values) we can open new PRs.

**Comment by docNord** [comment]
In what way can I be of assistance?

**Comment by mgcth** [comment]
Approve all PRs and I'll try to clean it up.

**Comment by mgcth** [comment]
I forced pushed a new history so every commit has a new sha now. Don't think there was any other way around it, but the file and 2 commits related to it are purged. For reference, this was the file

`src_files/data.csv`

and commit sha
`e75202a00824653ea7160137999c8cd5bbbf8bbb`
`f38c2ed1facb3afe51b1b915012cc17dffef2085`

Easiest would be to make a fresh clone.

@docNord, close this when you've seen it.
