### ISSUE TITLE
ifk-smhi

### ISSUE THREAD

**Issue by mgcth** [Ingenjorsarbete-For-Klimatet/ifk-smhi#34]
Create a Python package that parses most of SMHI's Open API data, see https://opendata.smhi.se/apidocs.

**Comment by docNord** [comment]
Main class functionality to be developed:

1) Easily find list of parameters (more or less done).
2) Easily find available stations - searchable through 
    a) station name
    b) city name (via geopy geocode)
    c) latitude and longitude
    d) all stations with given parameter within area
3) Strång / Mesan suggested as interpolation means when applicable
4) Filling missing data when 3 is not applicable:
    a) Linear interpolation
    b) using mean value from nearby stations within radius r,
