### ISSUE TITLE
mypy doesn't fail

### ISSUE THREAD

**Issue by mgcth** [Ingenjorsarbete-For-Klimatet/ifk-smhi#37]
For commit, [0323f6e](https://github.com/Ingenjorsarbete-For-Klimatet/ifk-smhi/pull/35/commits/0323f6e86095fef729679f8aca2d783e0a63119f) mypy check should fail at least at https://github.com/Ingenjorsarbete-For-Klimatet/ifk-smhi/blob/0323f6e86095fef729679f8aca2d783e0a63119f/src/smhi/smhi.py#L118 but it doesn't.

**Comment by docNord** [comment]
The commit referenced is no longer available. No new problems of the sort have appeared, and it seems `mypy` does its job in these days. Perhaps time to close the issue? We could always re-open it when needed.

**Comment by docNord** [comment]
No response in a week - I am closing.
