### ISSUE TITLE
Metobs usability

### ISSUE THREAD

**Issue by mgcth** [Ingenjorsarbete-For-Klimatet/ifk-smhi#38]
**Description**

As of now, `Metobs` is the class a user is intended to use to call the Metobs SMHI API. It has several methods that need to be called in sequence, like `__init__` (gets the available versions needed for the next method), `get_parameters`, `get_stations` etc. These methods are named `get_` but don't return anything, instead they mutate the state of the `Metobs` object.

I think this is _idiomatic_, i.e. either return or mutate but not both. However, the name is a bit misleading, I think.

**Proposal**

Two possibilities.

1)
Once our code was similar to a `set_` method. For example, we would call it like

```Python
client = Metobs()
client.set_parameter(parameter)
```

The `set_parameter` method would the mutate `client` and fetch all available ´stations` for that `parameter´. In comparison, now we call `client.get_stations(parameter)` which mutates `client` and fetches all available `stations` for `parameter` (which to me makes more sense, apart from a get method mutation `client`).

For this, we could use the setter property, e.g.
```Python
class Metobs:
    def __init__(self):
        ...

    @parameter.setter
    def parameter(self, parameter)
    
```

and would be called like

```Python
client = Metobs()
client.parameter = parameter
```

2)
Rename the current `get_` methods, but not sure to what if the behaviour isn't changed. If we return, methods shouldn't mutate and there is little point in the `Metobs` class at all, see below.

**Alternative**

We could instead rely on users creating the _subclasses_, like `MetobsParametersV1` and `MetobsStationsV1` manually. They are essentially immutable (contain only an `__init__` method). Something like

```Python
parameters = MetobsParametersV1(versions)
stations = MetobsStationsV1(parameter)
...
data = MetobsDataV1(parameter, station, ...)  # or something like that
```

Maybe we could allow for both uses?

**Comment by docNord** [comment]
It sounds as though you are leaning towards 1)? I am fine with that.

**Comment by mgcth** [comment]
This will be taken care of issue #41 and PR #43.
