### ISSUE TITLE
Metobs (sub)class names

### ISSUE THREAD

**Issue by mgcth** [Ingenjorsarbete-For-Klimatet/ifk-smhi#39]
**Description**

The `Metobs` class name is fine. However, we could rename

- `MetobsParametersV1`-> `Parameters`
- `MetobsStationsV1`-> `Stations`
- `MetobsPeriodsV1`-> `Periods`
- `MetobsDataV1`-> `Data`

as they are confined to the `metobs` namespace (in the `metobs.py` file). There should be little chance of user confusion with other SMHI APIs, like STRÅNG and MESAN.

**Comment by docNord** [comment]
Sounds reasonable. Will be less cumbersome a read, for one thing.
