### ISSUE TITLE
Metobs API call dependency data structure

### ISSUE THREAD

**Issue by mgcth** [Ingenjorsarbete-For-Klimatet/ifk-smhi#40]
**Description**

The Metobs API can be called directly, which we support if a user knows all the intermediate parameters, stations etc. The goal of the `Metobs` module is to provide some sort of inspection of the intermediate steps.

As of [4d3e8ff](https://github.com/Ingenjorsarbete-For-Klimatet/ifk-smhi/commit/4d3e8ff0c4d2e50a241106b7cd1424da612acdaf), we mutate the `Metobs` class with each `get_` method.

The Metobs API basically forms a linked list data structure, e.g.

`Versions -> Parameters -> Stations -> Periods -> Data`

That is, `Parameters` depend on `Versions`. So, if `Versions` change, `Parameters` isn't valid anymore (or any subsequent node).

Essentially, the `Metobs` class would be of a `LinkedList` type and `Versions`, `Parameters` etc. would be of a Node type.

**Proposal**

Our `Metobs` class should at least try to emulate a linked list in the behaviour described above, if not be of a LinkedList type. If the `Parameters` node is recreated, there are no links to the old `Stations->Periods->Data` lineage.

**Comment by docNord** [comment]
Yes! This makes perfect sense - we'll put!

**Comment by mgcth** [comment]
See discussion in #41.
