### ISSUE TITLE
Metobs inspect API and get data

### ISSUE THREAD

**Issue by mgcth** [Ingenjorsarbete-For-Klimatet/ifk-smhi#41]
**Description**

The `Metobs` class has two purposes. It helps the user inspect the API and also get data (and intermedia data).

**Proposal**

Could we separate the behaviour into two separate classes?

For inspection
`Metobs` (we should avoid verbs for class names like `Inspect`, maybe `Inspector` could work?)

For retrieving data
`Data`

They could be used together when the user needs to inspect the API. Otherwise, the `Inspector` class could be omitted. For example

```Python
inspector = Inspector()
inspector.get_versions()
inspector.get_parameters(version)
# etc, as Metobs works now
```

And `Data`

```Python
data = Data(version, parameter, station, period, data_type)
```

similar to `get_data_from_selection` in `Metobs`.

**Comment by docNord** [comment]
That might be a good idea, yes. How do you envision the call structure would look at the user stage? The Inspector is not going to be part of static codes at all, I suppose... Well that may also improve readability.

**Comment by mgcth** [comment]
We could have something like this

```Python
versions = Versions()  # defaults to "1.0", only supported
parameters = Parameters(versions, 1)
stations = Stations(parameters, 1)
periods = Periods(stations, 1)
data = Data(periods)  # defaults to "corrected-archive" in periods
```

Python doesn't really have immutable types, but as above the user wouldn't need to mutate the created objects. They can just create a new object instead.

We could use `Metobs` for inspection, or one could do

```Python
versions.data
#  prints list of available versions

parameters.data
#  prints list of all parameters for that version

stations.data
#  prints list of all stations for that parameter

periods.data
#  prints list of all periods for that station

data.data
#  pandas DataFrame
```

**Comment by docNord** [comment]
I think this is really good - it is concise and makes it easy to refer back. The classes should have default values as well, however, at least parameters. 

`parameters = Parameters(versions = 1.0)`

It feels reasonable to attempt to give an answer when there is limited input, especially as "versions" isn't really in use at this stage.

Perhaps we can come up with defaults down the line too?

Anyway, I like this setup.
