### ISSUE TITLE
Returned data (and headers)

### ISSUE THREAD

**Issue by mgcth** [Ingenjorsarbete-For-Klimatet/ifk-smhi#44]
**Description**

To move this to a release version, we should consider a unified data format. Metobs returns a pandas DataFrame, and the other APIs return a list of dicts, I think.

**Proposal**

Unify this to something, maybe a pandas DataFrame or list of some sort?

**Comment by docNord** [comment]
I think a dataframe makes the most sense, and I think the index should be
datetime (like in the upcoming metobs)

**Comment by docNord** [comment]
I do not get any data from Mesan when I run the code in the example - just a header:

```python
from smhi.mesan import Mesan

client = Mesan()
headers, data = client.get_point(16, 58)
```
