### ISSUE TITLE
Metobs integration test hard-codes date

### ISSUE THREAD

**Issue by docNord** [Ingenjorsarbete-For-Klimatet/ifk-smhi#45]
In the Metobs integration test, the date range is explicitly hard-coded when downloading data from Karesuando (the header when reading corrected-archive, which is compared using string comparison, is changed in the data file monthly), causing a monthly recurring bug.

@mgcth can you have a look at this?

**Comment by mgcth** [comment]
Great that you found it!

**Comment by mgcth** [comment]
Writing here for documentation, but see #43, too.

@docNord, for tests to pass, we could have a `{{ date }}` key in the `head` string and do

`head = head.replace("{{ date }}", datetime.date.today().strftime("%Y-%m-%d"))`
