### ISSUE TITLE
Add functionality to smhi client

### ISSUE THREAD

**Issue by docNord** [Ingenjorsarbete-For-Klimatet/ifk-smhi#50]
Improve SMHI client, currently working as umbrella with call structure for `Metobs` only, with:

- [ ] Call structure including city name call for `strang`
- [ ] Call structure including city name call for `mesan`
- [ ] Call structure including city name call for `metfcts`
- [ ] Augment code to fit new output structure from #44 into SMHI class object.

See also #29.

**Comment by mgcth** [comment]
I'll look into this soon (as in days :))
