### ISSUE TITLE
Only getting up until 2022-11-01 when reading "Lufttemperatur" from Borås

### ISSUE THREAD

**Issue by docNord** [Ingenjorsarbete-For-Klimatet/ifk-smhi#59]
I suspect there might be some sort of hiccup in the data parsing which is causing this, as the header says that data should be available up until yesterday, essentially.

**Comment by mgcth** [comment]
This isn't really a bug in `ifk-smhi`, but just how SMHI stations store and serve data.

Do

```python
p_ = Parameters()
s_ = Stations(p_, 1)
pe_ = Periods(s_, 72450)  # Borås
pe_.data
```

will show

```python
>>> ('corrected-archive', 'latest-day', 'latest-hour', 'latest-months')
```

The corrected archive usually does not contain the `latest-months` (by default 3 months or so), and that makes sense from the title.

So if you want both you'll have to do

```python
d_hist = Data(pe_, "corrected-archive")
d_current = Data(pe_, "latest-months")
d_all = d_hist.data.append(d_current.data)
```

**Comment by docNord** [comment]
Awesome, thanks!
