### ISSUE TITLE
Reduce method side effects

### ISSUE THREAD

**Issue by mgcth** [Ingenjorsarbete-For-Klimatet/ifk-smhi#66]
**Description**

Reduce or eliminate (as much as possible) side effects from our methods. Along these lines, remove the Metobs class altogether and just use the individual components.

**Comment by docNord** [comment]
How do you think the structure should be in order to avoid such side effects, and what side effects are you thinking of?

**Comment by mgcth** [comment]
We could probably delete this class altogether

https://github.com/Ingenjorsarbete-For-Klimatet/ifk-smhi/blob/6be598b6eba0199b221f237b337887c4951e69fd/src/smhi/metobs.py#L12

For example, `get_periods` doesn't actually return anything, but just mutates an internal state `periods` of the object

https://github.com/Ingenjorsarbete-For-Klimatet/ifk-smhi/blob/6be598b6eba0199b221f237b337887c4951e69fd/src/smhi/metobs.py#L74-L93

I think it makes the code harder to test and reason about, and as a user, I would expect `get_` to return something and not modify the object state.

**Comment by mgcth** [comment]
Maybe we should try to release version 0.1.0 first :)

**Comment by docNord** [comment]
Good point :)
