### ISSUE TITLE
Mesan parameter listing

### ISSUE THREAD

**Issue by docNord** [Ingenjorsarbete-For-Klimatet/ifk-smhi#82]
Currently, the output from calling Mesan parameters is appalingly difficult to read (a json dictionary style list which does not read well). There should be a function which writes the names of the parameters similar to the Metobs parameters function.

```
from smhi.mesan import Mesan
client =Mesan()
client.parameters

#Reads better, example:
import pandas as pd
df = pd.DataFrame(client.parameters)
df["name"]
```

**Comment by mgcth** [comment]
I'm not sure a data frame is the correct format here. How about a dataclass, in that way we can keep the schema fixed?
