### ISSUE TITLE
index error when using interpolate with get_data

### ISSUE THREAD

**Issue by kjohan19** [Ingenjorsarbete-For-Klimatet/ifk-smhi#89]
I was playing around with the smhi client and tried to use interpolate. I got a dict cannot have index error and took a closer look at the code. It seems like there is a small bug with the order in which the get_data values are assigned. It can be found in line 169 in smhi.py and looks like this:
`_, tmpdata = self.get_data(parameter, nearby_station[0])`
I think you only need to switch places on the underscore and tmpdata and it will do as intended.

Thank you for providing this client!

Br,
Karl

**Comment by docNord** [comment]
Thank you for noting. I will try to get a bugfix in tonight.
