### ISSUE TITLE
'Datum' is not returned for parameter no 2

### ISSUE THREAD

**Issue by docNord** [Ingenjorsarbete-For-Klimatet/ifk-smhi#91]
It seems MetObs is having trouble parsing data returned for parameter 2 (and possibly other?). We should explore why and adapt the code to allow reading all signals.

**Comment by mgcth** [comment]
For parameter 2, these columns are returned

```python
Index(['Datum Tid (UTC)', 'Till Datum Tid (UTC)', 'Representativt dygn'], dtype='object')
```

**Comment by mgcth** [comment]
We could add a test for each parameter type

https://github.com/Ingenjorsarbete-For-Klimatet/ifk-smhi/blob/f6bbae6e1758c75644eb41ae150ba3bfc6cbcc7a/tests/integration/test_integration_metobs.py#L171

And really, we should probably test the other APIs for different parameters (or throw an exception if we haven't tested it). Something you want to do @docNord? Adding tests shoudl be easy and just update the code as needed at

https://github.com/Ingenjorsarbete-For-Klimatet/ifk-smhi/blob/f6bbae6e1758c75644eb41ae150ba3bfc6cbcc7a/src/smhi/metobs.py#L595
